# Generated by Django 3.0 on 2021-03-24 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='qty',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
